engines:
  duplication:
    enabled: true
    config:
      languages:
      - python:
          python_version: 3
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_patterns:
  - "tests.py"
